[package]
name = "p4475-assets"
description = "Staging-only compatible asset importer for KartRider P4475"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "p4475-assets"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
p4475-core = { path = "../p4475-core" }
p4475-rho5 = { path = "../p4475-rho5" }
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
